apiVersion: v1
kind: Service
metadata:
  name: sats-kit-server
  labels:
    app: sats-kit-server
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 3001
      name: http
  selector:
    app: sats-kit-server
---
apiVersion: v1
kind: Service
metadata:
  name: sats-kit-client
  labels:
    app: sats-kit-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: sats-kit-client
