apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascend-api
  labels:
    app: ascend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascend-api
  template:
    metadata:
      labels:
        app: ascend-api
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ascend-api
          image: ghcr.io/dylanvanh/ascend-api:v0.1.6
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ascend-config
            - secretRef:
                name: ascend-secret
          ports:
            - containerPort: 8787
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascend-web
  labels:
    app: ascend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascend-web
  template:
    metadata:
      labels:
        app: ascend-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ascend-web
          image: ghcr.io/dylanvanh/ascend-web:v0.1.8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
