apiVersion: v1
kind: Service
metadata:
  name: sidebet-api
spec:
  selector:
    app: sidebet-api
  ports:
    - name: http
      port: 8787
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: sidebet-discord-bot
spec:
  selector:
    app: sidebet-discord-bot
  ports:
    - name: http
      port: 8788
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: sidebet-web
spec:
  selector:
    app: sidebet-web
  ports:
    - name: http
      port: 80
      targetPort: http
