apiVersion: v1
kind: Service
metadata:
  name: portfolio-app
  labels:
    app: portfolio
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: portfolio
