services:
  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - pixel-pythons
      - portfolio
      - investec
      - ollama
      - nuke
      - strava-bot
      - hevy-progressive-overloader
    restart: unless-stopped

  pixel-pythons:
    build: ../pixel-pythons
    container_name: pixel-pythons-app
    expose:
      - "3001"
    restart: unless-stopped

  portfolio:
    build: ../portfolio
    container_name: portfolio-app
    expose:
      - "80"
    restart: unless-stopped

  investec:
    build: ../investec-transaction-buckets
    container_name: investec-app
    env_file: ../investec-transaction-buckets/.env
    expose:
      - "8080"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-app
    expose:
      - "11434"
    restart: unless-stopped

  nuke:
    build: ../btc-transaction-nuke
    container_name: nuke-app
    env_file: ../btc-transaction-nuke/.env
    expose:
      - "3000"
    restart: unless-stopped

  strava-bot:
    build: ../strava-bot-rust
    container_name: strava-bot
    env_file: ../strava-bot-rust/.env
    expose:
      - "8081"
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle/data:/data
    ports:
      - "9999:8080"
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    restart: unless-stopped

  hevy-progressive-overloader:
    build: ../hevy-progressive-overloader
    container_name: hevy-progressive-overloader-app
    env_file: ../hevy-progressive-overloader/.env
    expose:
      - "3005"
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "${LAN_IP}:53:53/tcp"
      - "${LAN_IP}:53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      TZ: 'UTC'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
      FTLCONF_dns_upstreams: '1.1.1.1;8.8.8.8'
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-storage: {}
