apiVersion: v1
kind: Service
metadata:
  name: dietdial-web
  labels:
    app: dietdial-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: dietdial-web
