apiVersion: v1
kind: Service
metadata:
  name: investec
  labels:
    app: investec
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: investec
