apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuke
  labels:
    app: nuke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuke
  template:
    metadata:
      labels:
        app: nuke
    spec:
      containers:
        - name: nuke
          image: ghcr.io/dylanvanh/btc-transaction-nuke:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
