global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pihole"
    static_configs:
      - targets: ["pihole-exporter:9617"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
