apiVersion: v1
kind: Service
metadata:
  name: pixel-pythons
  labels:
    app: pixel-pythons
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  selector:
    app: pixel-pythons
